[metadata]
name = {{LIBRARY_NAME}}
version = {{VERSION}}
description = {{SHORT_DESCRIPTION}}
long_description = file: README.md
long_description_content_type = text/markdown
author = {{AUTHOR_NAME}}
author_email = {{AUTHOR_EMAIL}}
license = {{LICENSE_TYPE}}
url = {{GITHUB_URL}}

[options]
packages = find:
python_requires = >=3.8
include_package_data = True

[options.extras_require]
dev =
    pytest
    sphinx
    sphinx_rtd_theme